### ISSUE TITLE
Welcome message with userlist

### ISSUE THREAD

**Issue by Anthony-gamer** [C-Bouthoorn/Anthony-Server#11]
We need a second message to be sent out to the user who just logged in saying something like this:
```
Users online(4): user1, user2, BBBuserwithID3, AAAuserwithID4
```
Also, make it into a **/online** command. Idea is to order people by ID, not by name.

After that message, another message with this should come up for the user who just logged in:
```
Welcome to the server! Use "/help" to see all the commands you have access to.
```
Note: It should be **"/help"**

**Comment by C-Bouthoorn** [comment]
>  Idea is to order people by ID, not by name.
I'd suggest the following order: Type (Admins first, then Mods, then normal players). They are then sorted by id. (Thus join date)

> Note: It should be "/help"
Including quotes?

**Comment by Anthony-gamer** [comment]
> Including quotes?
Excluding quotes, sorry. Will fix.

**Comment by C-Bouthoorn** [comment]
Okii, done that
