### ISSUE TITLE
TODO: Layout /help

### ISSUE THREAD

**Issue by Anthony-gamer** [C-Bouthoorn/Anthony-Server#12]
Below is what to use as base for layout of **/help**

> **/fur [color]:**
> Changes your fur to indicated color. e.g. /fur red or /fur #ff0000
> **/mane [color]:**
> Changes your mane to indicated color.
> **/tailstyle [style]:**
> Changes your tail to indicated style. e.g. /tailstyle derpy or /tailstyle applejack
> **/manestyle [style]:**
> Changes your mane to indicated style.
> **/fullstyle [style]:**
> Changes your mane and tail to indicated style.
> **/online:**
> Shows you who is online.
> **/spawn:**
> Teleports you to the spawn.
> **/sethome:**
> Sets your private spawn point to your current location.
> **/home:**
> Teleports you to your private spawn point.
> **/tag:**
> Join/leave the tag.
> **/rules:**
> Displays the rules.
> **/create [name]:**
> Creates a chatchannel.
> **/join [name]:**
> Joins a chatchannel.
> **/leave [name]:**
> Leaves a chatchannel. (You cannot leave certain default channels)
> **/teleport [name]:**
> Teleports you to a player.
> **/report [name] [reason]:**
> Report a player. Troll reports will be punished!

**Comment by C-Bouthoorn** [comment]
_Meh, can't assign multiple people_

I'll implement the availability for commands, and I'll let you ( @Anthony-gamer ) implement the specific commands.

Do we need a new column in the database to store this information (furcolor, manecolor, tailstyle, ...) ?

**Comment by Anthony-gamer** [comment]
I was thinking of having a separate table with all the pony-data. Stores furcolor, manecolor, tailstyle, manestyle, home.x, home.y, gender (might use male/female textures)

**Comment by C-Bouthoorn** [comment]
This is already fixed in `commands.coffee`. I've included all commands available, it's up to you to fill them in
