### ISSUE TITLE
Command handling: Else If/Switch

### ISSUE THREAD

**Issue by Anthony-gamer** [C-Bouthoorn/Anthony-Server#13]
Wouldn't it be better (and possibly cleaner) if we used the Switch statement instead of a bunch of Else-Ifs?

[W3Schools - Javascript Switch Statement](http://www.w3schools.com/js/js_switch.asp)

**Comment by C-Bouthoorn** [comment]
Hmnn, dunno. Break statements are terrrrrible

**Comment by Anthony-gamer** [comment]
Why are they terrible? Switch-statements make everything look much cleaner. Only caveat is that in order to define the "end" of a matching Switch, you have to put "break;"

**Comment by C-Bouthoorn** [comment]
As stated on http://stackoverflow.com/questions/2922948/javascript-switch-vs-if-else-if-else it doesn't make much difference, unless it's more readable. 

*edit* So I tried it, and it is more readable. Pushing in 3...2...1...

**Comment by C-Bouthoorn** [comment]
Also, as stated on http://coffeescript.org/#switch there is no `break` needed :wink:
