### ISSUE TITLE
TODO: Check for user already logged in at login

### ISSUE THREAD

**Issue by Anthony-gamer** [C-Bouthoorn/Anthony-Server#16]
We need a check at login to see if the user specified is already logged in or not.

Code should be inserted at **server.coffee:464**, right after this line:
`console.log "[ LOG-IN ]".black.bgYellow + " #{ip} : Login request for user '#{username}'"`

EDIT: Changed line from 463 to 464

**Comment by C-Bouthoorn** [comment]
`black.bgYellow`  `black.bgYellow`  `black.bgYellow`  `black.bgYellow` 

As sung by Wiz Khalifa

**Comment by C-Bouthoorn** [comment]
_Note: If you're using linenumbers, please specify the version. In https://github.com/C-Bouthoorn/Anthony-Server/commit/ca08b63f8b9d579659de47eed5f03da8673ee089 it's line :483_
