### ISSUE TITLE
MY NAME IS NOT HTMLInputElement

### ISSUE THREAD

**Issue by C-Bouthoorn** [C-Bouthoorn/Anthony-Server#7]
Welcome to our server, [object HTMLInputElement] !

**Comment by Anthony-gamer** [comment]
Fixed, also updated text.

Changes below:
[server.coffee](https://github.com/C-Bouthoorn/Anthony-Server/commit/9118757fe0b4fd44d453d80fef43dbb110a0b0cb)
[www/index.coffee](https://github.com/C-Bouthoorn/Anthony-Server/commit/9198ee599cc99fa636d0cce289d78cf76b69f884)
